### ISSUE TITLE
PATCH /session/account -> 409 "data.id must be '{id}'" error

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#100]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change username or password, user send a `PATCH /session/account` request with the changed attributes. The [JSON API Spec](http://jsonapi.org/format/#crud-updating) which we comply with requires an update request to send `data.id`. So in theory a user could send a `data.id` of an account which is not theirs.

### :dart: The goal

Compare the `data.id` from request payload with the `account.id` of the account. If they diverge, return a `409 Conflict` error with the message `"data.id must be '{id}'"`, where `{id}` is the current user’s account id

### :clipboard: Step by Step

- [x] claim this issue (@seanjohnite)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/ebf2591dbb8c0c228bce4a6c664ebf88adcf0fed/tests/integration/routes/account/patch-account-test.js#L108-L129)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account -> 409 "data.id must be '{id}'" error`
- [x] Start a Pull Request: #116
- [x] Implement :)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account -> 409 "data.id must be '{id}'" error`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by seanjohnite** [comment]
Can I try this one?

**Comment by gr2m** [comment]
Absolutely, all yours Sean :)

**Comment by seanjohnite** [comment]
Thanks gr2m! I saw your talk at BostonJS and was compelled to check out these starter issues : ).

**Comment by gr2m** [comment]
fixed by https://github.com/hoodiehq/hoodie-server-account/pull/116

**Comment by gr2m** [comment]
Welcome Sean :wave: :dog: Thanks a lot for your first contribution to Hoodie, your fix was just released in [hoodie-server-account@2.6.11](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.11) :clap: 

Are you on twitter? Would you mind us giving you a shout out? 

I’d love to hear how you liked the experience, and if you have any idea how we can improve it? We are always eager to hear about motivation and earlier experiences for new contributors, so much to learn from for us :)

**Comment by seanjohnite** [comment]
I am on twitter at the same handle as github and would be fine with a shoutout! Thanks for the invite to the team!

The experience was great! I really appreciated the step by step instructions. I'm not super familiar with Hapi (mostly worked with the Express framework), so there was a bit of a learning curve to figure out what was going on. Perhaps if there was a general readme about the structure of the particular application?

I would definitely be interested in some additional contributions, if there's anything that comes to mind that you think might be manageable.

**Comment by gr2m** [comment]
Hey @seanjohnite, I found something you might be interested in, this time it’s on the Hoodie client side, so no Hapi. 

The [hoodie-client-connection-status](https://github.com/hoodiehq/hoodie-client-connection-status) repo has only 98% test coverage, and we try to have 100% in all our repos. Would you like to look into that? I can make an issue with a few instructions, the instructions will be very similar to this one here: https://github.com/hoodiehq/hoodie-client-account/issues/66
