### ISSUE TITLE
GET /session/account/profile: "404 Admins have no profiles" error

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#101]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

We differentiate between normal user accounts that you can sign up for with `PUT /session/account` and admin accounts which are configured in the app configuration. The latter have no account or profile, they are only used to manage other accounts and other app settings.

`GET /session/account/profile` is already implemented correctly, the only problem is that we currently respond with a `403` status code, although after discussing it we agreed that `404` would be the better error code here.

### :dart: The goal

For admin users, `GET /session/account/profile` should respond with `404 Not found` and the error message "Admins have no profiles"

### :clipboard: Step by Step

- [x] claim this issue (@ederribeiro)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the assertion in [tests/integration/routes/profile/get-profile-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/455350176c87a53e1eab8ae849370b1938cfbb58/tests/integration/routes/profile/get-profile-test.js#L91-L93) to test for `404` and the desired error message
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): GET /session/account/profile error for admins`
- [x] Start a Pull Request: #114
- [x] Implement :) 
- [x] Make sure tests pass. Commit with `fix(routes): GET /session/account/profile error for admins`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by ederribeiro** [comment]
Hello,
I want to solve this issue...

**Comment by gr2m** [comment]
All yours Eder :+1:

**Comment by gr2m** [comment]
released as [v2.6.8](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.8) :ok_hand:

**Comment by gr2m** [comment]
Would you mind us give you a shout out at https://twitter.com/hoodiehq? Your twitter account is https://twitter.com/ApuSoft – right?

I’ve also missed to invite you to our Contributors team at Hoodie, you should see the invitation at https://github.com/hoodiehq. We would love to welcome you :)

If you feel like contributing again, let us know :) We are out of starter issues, but there are other things you could work on if you like, I’m sure we can find something interesting
