### ISSUE TITLE
PATCH /session/account/profile -> 204

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#102]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change profile data, user send a `PATCH /session/account/profile` request with the changed attributes. Right now the server responds with `200` and the profile properties.

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/profile/update), the server should respond with an empty `204`

### :clipboard: Step by Step

- [x] claim this issue (@antoinelyset)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/6ba8cf6be7da74743defdeb149b6199ef9055219/tests/integration/routes/profile/get-profile-test.js#L64-L67)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account/profile -> 204 `
- [x] Start a Pull Request: #117
- [x] Implement :)  
     :rotating_light: Spoiler alert: compare with https://github.com/hoodiehq/hoodie-server-account/issues/99
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account/profile -> 204 `
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by antoinelyset** [comment]
Hi everyone ! I don't really understand if this issue if for the PATCH or the GET method. The uncommented test is for a GET call. Am I missing something ?

**Comment by gr2m** [comment]
Copy & Paste fail by me, I’m sorry, I’ll look into it asap and clarify the instructions :)

**Comment by gr2m** [comment]
okay, can you remove the commented out lines entirely from the `get-profile-test.js` file, and move them here instead: https://github.com/hoodiehq/hoodie-server-account/blob/6ba8cf6be7da74743defdeb149b6199ef9055219/tests/integration/routes/profile/patch-profile-test.js#L79-L82

Sorry, I’ve put them into the wrong file :(

**Comment by gr2m** [comment]
merged via #117. Released in [hoodie-server-account@2.6.13](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.13)

Thanks and for another contribution to Hoodie :tada: 

If you would like to contribute more, we don’t have any starter issues at this point, but a few other things were you could help us, if you like. Just ping me, I’m in our [Hoodie Chat](http://hood.ie/chat/) most of the time during Boston daytime ours :)

Last but not least, are you on twitter? Would you mind us giving you a shout out? We <3 new contributors, and we didn’t give you a shout out the last time I think?

**Comment by antoinelyset** [comment]
Of course ! I'm @antoinelyset on Twitter.

**Comment by gr2m** [comment]
Awesome thanks :) We gave you a shout out in our latest TGIF, too http://hood.ie/blog/lave-revision-artificial-maker.html Thanks again for your contribution!
