### ISSUE TITLE
PATCH /session/account/profile -> 409 "data.id must be '{id}'" error

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#104]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change a profile, user send a `PATCH /session/account` request with the changed attributes. The [JSON API Spec](http://jsonapi.org/format/#crud-updating) which we comply with requires an update request to send `data.id`. So in theory a user could send a `data.id` of a profile which is not theirs.

### :dart: The goal

Compare the `data.id` from request payload with the profile id of the current user. If they diverge, return a `409 Conflict` error with the message `"data.id must be '{id}'"`, where `{id}` is the current user’s profile id

### :clipboard: Step by Step

- [x] claim this issue (@tnguyen14)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/b8fe191d6ce6f5215dbef4675db56e25db376857/tests/integration/routes/profile/patch-profile-test.js#L119-L140)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account/profile -> 409 "data.id must be '{id}'" error`
- [x] Start a Pull Request. #121
- [x] Implement :)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account/profile -> 409 "data.id must be '{id}'" error`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by tnguyen14** [comment]
I'd love to tackle this if possible (I'm completely new to the hoodie project).

**Comment by gr2m** [comment]
@tnguyen14 welcome Tri :) The issue is all yours

**Comment by gr2m** [comment]
merged via #121, released as [v2.6.17](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.17).

Congratulations and thank’s a lot :bouquet: for your first PR to Hoodie :) We have invited you to the contributors team. If you like you can accept the invitation at https://github.com/hoodiehq. As Hoodie Team member you can push directly to our main repositories, no need to do forks. That makes it simpler to collaborate. Also you are part of a fun bunch of folks :)

Are you on twitter? We love giving new contributors a shout out with our [@hoodiehq](http://twitter.com/hoodiehq) twitter account, if you like?

**Comment by tnguyen14** [comment]
Many thanks @gr2m! this is honestly the best contributing experience to an open source project I've had (not that I've had many to compare to). Really appreciate your patience and guidance throughout. I am on twitter `@tridnguyen`.
