### ISSUE TITLE
implement GET /session/account/profile

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#11]
The `/session/account/profile` route is for accessing and changing non-sensitive user data

---

- [x] claim this issue (@patriciagarcia)
- [x] start a pull request (#62)
- [x] write tests for `GET /session/account/profile` in [tests/integration/routes/account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/integration/routes/account-test.js)
- [x] implement `GET /session/account/profile`
- [ ] update README
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

**Comment by patriciagarcia** [comment]
I'll take this one

**Comment by patriciagarcia** [comment]
Missing updating the README yet :-) (but PR ready for review)
