### ISSUE TITLE
POST /accounts Add test for 401 because of invalid session

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#125]
<a href="https://ti.to/hoodie/dc-meet-the-hoodies"><img width="664" alt="This issue is prepared for our Meet The Hoodies event in Washington DC on March 20th" src="https://cloud.githubusercontent.com/assets/39992/13901581/169ced44-edff-11e5-93d7-aaf3ef673fbc.png"></a>

### :dart: The goal

When running `npm test` then all specifications from the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#) that we implement
should be tested. Creating an account with [POST /accounts](http://docs.accountjsonapi.apiary.io/#reference/admins/user-account-collection/create)
defines a `401` response with a `Session invalid` error message. This can occur
the currently signed in user is not an admin. We do not test that yet, and the
goal of this issue is to create this test to make sure the server behaves correctly
and does not accidentally break in future.

### :clipboard: Step by Step

- [ ] claim this issue (comment below)
- [ ] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [ ] Add test to [tests/integration/routes/accounts/post-accounts-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/44627dfb559839f129ded74350a85a27ef5b2b2a/tests/integration/routes/accounts/post-accounts-test.js#L72-L75). Compare to [tests/integration/routes/account/get-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/44627dfb559839f129ded74350a85a27ef5b2b2a/tests/integration/routes/account/get-account-test.js#L62-L75)
- [ ] Make sure tests fail when you run `npm test`
- [ ] Commit with `test(routes): POST /accounts -> 401 for invalid session`
- [ ] Start a Pull Request. Mention `closes #125` in the description.  
      If this is your first, welcome :tada: :smile:
      [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
      on how to send a pull request
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by Oladele** [comment]
I'm looking into  this right now.

**Comment by gr2m** [comment]
Woop welcome at Hoodie @Oladele \o/ The new version has been released as [v2.6.16](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.16) :+1:
