### ISSUE TITLE
POST /accounts?include=foobar

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#127]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :dart: The goal

When running `npm test` then all specifications from the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#) that we implement
should be tested. Creating an account with `POST /accounts?include=foobar` is forbidden because `foobar` is not a relation of `account`. See http://docs.accountjsonapi.apiary.io/#introduction/query-parameters. JSON API specifies that the server must respond with `400 Bad Request` in that case, which is a case that is currently not covered by our tests 

### :clipboard: Step by Step

- [x] claim this issue (@codyzu)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment the two assertions in [tests/integration/routes/accounts/post-accounts-test.js#](https://github.com/hoodiehq/hoodie-server-account/blob/0499a27a8bad9f12ff08c39ca10c81ac93cd5977/tests/integration/routes/accounts/post-accounts-test.js#L100-L111) and remove the `// prepared test for ...` comment. Ignore that it says 126 :) It’s the right now
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): POST /accounts?include=foobar -> 400`
- [x] Start a Pull Request #132
- [x] Make the test pass :) Check out how we validate the `?query` parameter in _TBD_ for comparison
- [x] commit with `fix(routes): POST /accounts?include=foobar -> 400`
- [x] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by codyzu** [comment]
Hello, I would enjoy getting involved and therefore claiming this issue (nice step by step, btw).

**Comment by gr2m** [comment]
released as [v2.6.19](https://github.com/hoodiehq/hoodie-server-account/releases/tag/)

Welcome at Hoodie @codyzu :) We love giving shout outs to new contributors on Twitter, do you have an account?

I don’t have anything out of my head that you could work, but please look around, these repositores are the ones we are currently working on for the upcoming Hoodie Release: https://github.com/hoodiehq/hoodie/tree/tent#why-is-there-no-code-in-this-repository

Let me know if you have any preference or any questions. You can also join us in our [Hoodie Chat](http://hood.ie/chat/) :)

**Comment by codyzu** [comment]
Thanks @gr2m !

You can find me on the twitters @codyzus

I'll find some time to look around and checkout the chat this weekend.

My preference is backend node.js. About me, I'm a software engineer with nearly 10 years experience in C, C++, C#, Java, and recently node.js. I'm looking to get involved in an interesting open source project where I can contribute with node.js... Let me know if you have any ideas of where I can help.

**Comment by gr2m** [comment]
Welcome @codyzu! One can tell that you have experience, your pull request was A+ :) 

We don’t have good docs on that yet so let me give you a quick summary about the Hoodie Architecture. 

Hoodie is basically a server that comes with authentication / user account logic as well as data persistence. For that Hoodie integrates with [CouchDB](http://couchdb.apache.org). The main idea is to hide away all these internals from users, so Hoodie comes with a frontend API, the Hoodie client, which you can add to your html app with a `<script>` tag, so that you can JavaScript methods like `hoodie.account.signUp(options)`, `hoodie.store.add(object)` or `hoodie.connectionStatus.check()`. Even though some of its code runs in the browser, it all looks like Node.js code, see the [Hoodie Account Client’s index.js](https://github.com/hoodiehq/hoodie-client-account/blob/master/index.js) for example. We use [browserify](http://browserify.org/) to compile the code for the browser before publishing.

The overall architecture looks something like this (it’s still a bit work in progress, but getting there)

```
hoodie
├── @hoodie/account
│   ├── @hoodie/account-client
│   └── @hoodie/account-server
├── @hoodie/store
│   ├── @hoodie/store-client
│   └── @hoodie/store-server
├── @hoodie/connection-status
└── @hoodie/log
```

All nodes above have corresponding repositories, like [hoodie](https://github.com/hoodiehq/hoodie/), [hoodie-account](https://github.com/hoodiehq/hoodie-account), [hoodie-account-server](https://github.com/hoodiehq/hoodie-account-server) etc.

For all the server code, we use [Hapi](http://hapijs.com/), which is a fantastic Node.js server framework, and I can definitely recommend to look into its code to learn how a good Node project looks like. All the core modules server parts are Hapi plugins, and soon we will allow to write your own Hoodie plugins (again) which will follow the same structure with folders for `client/` ,`server/` and `public/`.

If you look to something else to work on, you can make an issue for one of the open inconsistencies here: https://github.com/hoodiehq/hoodie-server-account/issues/83 and work on it yourself. I’m also happy to do call for a quick introduction? Would love to find out more about your motivation, I’m curious as I’m thinking a lot about how to improve the experience for new and existing contributors at Hoodie and Open Source in general
