### ISSUE TITLE
data.id is redundant in /account PATCH APIs

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hoodie-server-account#22]
For current user, the id can be assumed, and for the admin use case the id of the user to change is specified in the query string.
I think the only case where the id would be necessary in the data payload would be in the case where one wanted to change an account's id.  Would that ever be desirable though? I think probably not.

**Comment by gr2m** [comment]
Thanks for the review Mike!

I see how that bit is confusing, I agree it’s redundant. But we follow the JSON API spec here, which requires to send the `"type"` and the `"id"` in the request payload: http://jsonapi.org/format/#crud-updating
