### ISSUE TITLE
Change vs Update

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hoodie-server-account#23]
Just a semantics issue: the accounts API uses 'change', but profile uses 'update'.  The two both use PATCH, and appear to be doing the same kind of thing.  Consistency is good.  (for me, I would vote for update for both)

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/account-json-api/commit/a91c0eb4714cebf2656afc3a2a7b325db584cc4c
