### ISSUE TITLE
use complete lodash package instead of lodash.*

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#33]
@boennemann [says](https://github.com/hoodiehq/hoodie-server-account/commit/0beb8b981f97033f013237adebbc83fad463a4e4#commitcomment-15099179)

> I would use the complete lodash package for all server side code and the `require('lodash/objects/merge')` method for client side code:

> 1. maintenance is super high for the individual packages
> 1. for install time: saves roundtrips, not download size
> 1. we are deduping and bundling all dependencies for the final hoodie build. When `lodash` is used throughout all components (+greenkeeper) then we'll end up with just one lodash (also in memory). I think that the saved, duplicated metafiles of all the individual packages might have a similar size than the entire build :P
> 1. the `lodash/*/*` method has all the upsides of the individual packages for client side builds, without the package.json and require mess 

> :)

Sounds good to me

**Comment by janl** [comment]
https://github.com/hoodiehq/hoodie-server-account/pull/61
