### ISSUE TITLE
PUT /session to return 401 Unauthorized error when user cannot be found

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#52]
Currently the server returns `404 Not Found` which is not compliant with the specification:
http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-in

---

- [x] claim this issue (comment below or assign yourself)
- [x] setup and run tests as described here: https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md – there should be no failing test
- [x] [uncomment failing test](https://github.com/hoodiehq/hoodie-server-account/blob/e37cbdd5d364d1d1cffc583929fd17f8ca07eedf/tests/integration/routes/session-test.js#L143-L156). Test should fail now. 
- [x] Commit with `test: PUT /session to return 401 Unauthorized error when user cannot be found` and start a Pull Request
- [x] fix the issue (commit with `fix: PUT /session to return 401 Unauthorized error when user cannot be found`)
- [x] review & merge
- [x] update https://github.com/gr2m/milestones/issues/88
- [x] [uncomment integration test](https://github.com/hoodiehq/hoodie-app-something-tracker/blob/f961de1ba467ad67d6e24cd43dad1621ee855d78/test/account-test.js#L73-L75)

If you have any questions, comment or ping us in the [Hoodie chat](http://hood.ie/chat) or on [Twitter](https://twitter.com/hoodiehq)

**Comment by fgkramer** [comment]
I'll gladly take it

**Comment by gr2m** [comment]
all yours @fgkramer  :)

**Comment by gr2m** [comment]
@fgkramer, are you still looking into this?

**Comment by fgkramer** [comment]
Sorry, I've been busy and I hadn't had time to see this. Feel free to
reasign it and please accept my apologies.

2016-01-25 11:38 GMT-03:00 Gregor Martynus <notifications@github.com>:

**Comment by gr2m** [comment]
no worries at all @fgkramer :) I’ll remove our comments so people looking into it don’t get confused

**Comment by patriciagarcia** [comment]
The server returns [whatever the CouchDB mock throws](https://github.com/hoodiehq/hoodie-server-account/blob/e37cbdd5d364d1d1cffc583929fd17f8ca07eedf/tests/integration/routes/session-test.js#L145), currently 404, but I am not sure that is right.

 I was trying to sign in in CouchDB with a random username/password and I get `{"error":"unauthorized","reason":"Name or password is incorrect."}` instead of `404`.

**Comment by gr2m** [comment]
We don’t use CouchDB for authentication, but have our own implementation. We first lookup the user account [here](https://github.com/hoodiehq/hoodie-server-account/blob/master/api/sessions/add.js#L10) and then validate the passed password. But if the user cannot be found with `state.db.get('org.couchdb.user:' + options.username)`, the server returns a 404. 

We have an own implementation instead of using CouchDB’s auth APIs, as we want to work with PouchDB instances only. That’s why we created https://github.com/hoodiehq/couchdb-calculate-session-id, https://github.com/hoodiehq/pouchdb-users and https://github.com/hoodiehq/pouchdb-admins

Makes sense?

**Comment by patriciagarcia** [comment]
Ah, ok, so our server is logged as admin to the database and is just requesting the user document?

**Comment by gr2m** [comment]
there is no "logged in as admin" thing, really. You have a PouchDB instance for the users database that we can work directly against, without security (so we have to be careful with it). When you sign in, we try to find the user doc for the given username, if we find it, we validate the password by calculating the password hash for the password parameter with the hash in the user doc.

**Comment by patriciagarcia** [comment]
Ah, got it now, thanks!

**Comment by patriciagarcia** [comment]
Pending fix on the integration tests (@gr2m, all yours :-))

**Comment by gr2m** [comment]
done: https://github.com/hoodiehq/hoodie-app-something-tracker/blob/master/test/account-test.js#L98-L101
