### ISSUE TITLE
Implement PATCH /session/account

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#53]
The account update route is currently not implemented at all:
http://docs.accountjsonapi.apiary.io/#reference/current-user/account/update

---

- [x] claim the issue (@ianstalter123)
- [x] Start PR (#63)
- [ ] Add tests to [tests/integration/routes/account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/integration/routes/account-test.js)
- [ ] Implement the new route in [routes/acount.js](https://github.com/hoodiehq/hoodie-server-account/blob/master/routes/account.js) (not accounts.js, that’s for admins only)
- [ ] review & merge
- [ ] update https://github.com/gr2m/milestones/issues/88
- [ ] [uncomment integration test](https://github.com/hoodiehq/hoodie-app-something-tracker/blob/6c8b0f5a8aecb8fd3645bbb23782f6d3effd66af/test/account-test.js#L112-L136)

**Comment by ianstalter123** [comment]
Hey - this should be implemented in account.js as account update route right? I see there is already a patch route in accounts.js?

**Comment by gr2m** [comment]
@ianstalter123 exactly. the routes in accounts.js are for admins

**Comment by ianstalter123** [comment]
@gr2m yeah - looks like it should be pretty similar hopefully will give it a try - thanks.

**Comment by gr2m** [comment]
cool, let me know if you need any help :)
