### ISSUE TITLE
implement PATCH /session/account/profile

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#60]
The `/session/account/profile` route is for accessing and changing non-sensitive user data

---

- [x] claim this issue (@antoinelyset)
- [ ] start a pull request
- [ ] write tests for `PATCH /session/account/profile` in [tests/integration/routes/account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/integration/routes/account-test.js)
- [ ] implement `PATCH /session/account/profile`
- [ ] update README
- [ ] review & merge

Ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

**Comment by Jameskmonger** [comment]
What's the difference between this and `PATCH /session/account?include=profile`, @gr2m ?

**Comment by gr2m** [comment]
`PATCH /session/account?include=profile` updates account, but response includes profile. `PATCH /session/account/profile` updates profile. JSON API currently cannot update both at once, they are working on a spec / extension

**Comment by antoinelyset** [comment]
I would love to give a try :) (I don't want to block someone if this person if faster than me).

**Comment by gr2m** [comment]
Give it a shot @antoinelyset, you are not blocking anyone :) Let me know if you have any questions

**Comment by Jameskmonger** [comment]
That's fine @antoinelyset, I hadn't started - was just curious! Good luck :+1:

**Comment by gr2m** [comment]
Oh sorry @Jameskmonger, I didn’t meant to take it away from you, I didn’t know you planned to work on it. I’m happy to find something else for you to work on, ping me anytime in our hood.ie/chat or on twitter.com/gr2m

**Comment by Jameskmonger** [comment]
No @gr2m it wasn't sarcasm - I didn't plan to work on it! I was just looking into the code and trying to see what the difference between the two parts was :stuck_out_tongue: I hadn't planned to work on it at all :smile:
