### ISSUE TITLE
GET, PATCH, DELETE /session/account sould respond with 401 Invalid session, not 404 Not found

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#81]
### The problem

When sending a `GET /session/account` request with an invalid session, the server responds with 404, as this is what [`session.find`](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/account.js#L82-L84) returns.

### What we want

The correct way is to catch the `404` error and replace it with a `401` as we do it in [`GET /session/account/profile`](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/profile.js#L44-L51)

### Steps to fix

**Working on your first Pull Request?** You can learn how from this *free* series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) 

---

- [x] claim this issue (@matt-major)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Start a PR: #84
- [x] Adjust the test in [tests/integration/routes/account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/tests/integration/routes/account-test.js#L152-L164) to expect a `401 Invalid session` response, instead of the `404 Not Found` response
- [x] add a new test group within `PATCH /session/account` in the same file for `Session does not exist` and test for `401 Invalid session` response, move the current content into another group `Session does exist`. 
- [x] adjust the [DELETE /session/account without valid session test](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/tests/integration/routes/account-test.js#L318-L330) accordingly
- [x] make sure tests fail. Commit with `test(routes): /session/account 401 responses`
- [x] fix the behavior in [routes/account.js](https://github.com/hoodiehq/hoodie-server-account/blob/e9c1f0f0c84fccdab962531d61cabbe675da3c56/routes/account.js)
- [x] Make sure all tests pass. Commit with `fix(routes): /session/account 401 responses`
- [ ] Someone else: review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by matt-major** [comment]
PR #84 submitted to make this change.

**Comment by gr2m** [comment]
Great work, thanks a ton @matt-major :bouquet: Your work has been released in https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.2 :shipit: 

I’ve invited you to https://github.com/orgs/hoodiehq/teams/contributors, we’d love to welcome you. If there is anything we could improve with our "Starter" issues or with this issue in particular, we’d love to hear it, we always try to improve the experience for new and existing Hoodie contributors

If you’d like to pick another one, we have some more available here: http://go.hood.ie/hoodie-starter-issues. You can also remove the "starter" label to to see more challenging issues

**Comment by matt-major** [comment]
Thanks @gr2m! My pleasure.

I'll take a look at the other tasks that are available see what I can pick up for you.
