### ISSUE TITLE
PUT /session to return 401 Invalid credentials, not 401 Invalid password

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#85]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat: First Timers only

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

---

### :bug: The Bug

Our implementation diverges from our [JSON API specification](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-in). When trying to sign in with a valid username, but invalid password, the server will respond with the message `”Invalid password”`, while the specification says `”Invalid credentials”`

### :clipboard: Steps to fix

- [x] claim this issue (@breun)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Adjust the test in [tests/integration/routes/session-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/3a5db63/tests/integration/routes/session-test.js#L118) to assert that the server will respond with `”Invalid credentials”`.
- [x] Make sure tests fail when you run `npm test`. Commit with `test: 401 Invalid password -> 401 Invalid credentials`
- [x] Start a Pull Request.  
(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)
- [x] Implement the change :)
- [x] Make sure tests pass. Commit with `fix: 401 Invalid password -> 401 Invalid credentials`
- [x] You are done :clap: comment below that your pull request is ready for review 

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by breun** [comment]
I'm giving this a go!

**Comment by breun** [comment]
I forked the repository to my GitHub account, cloned it to my computer and ran `npm install`. Sadly that throws all kinds of connection errors:

```
~/Projects/hoodie-server-account $ npm install
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to nam
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Darwin 15.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v4.3.1
npm ERR! nam  v2.14.18
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! sys call read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with nam itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

The whole things seems to hang now. I'm not behind a proxy AFAIK.

**Comment by gr2m** [comment]
Weclome @breun, issue is all yours :)

I’m looking into the problem now.

**Comment by gr2m** [comment]
@breun I had no luck, I’m afraid. It might have been a temporary hiccup. Can you try this please:

```
$ rm -rf node_modules && npm_config_loglevel=silly npm install
```

And post the logs somewhere? It might be quite a lot, so maybe put it in a gist and link it here if possible. 
If it fails again, can you try to install something else? like `npm install --global npm@2` to update your npm to the latest 2.x.x version?

**Comment by breun** [comment]
I updated to npm 2.14.19 and tried again. It doesn't seem to be a temporary hiccup, I already retried twice before and `npm install` fails (and hangs) again: https://gist.github.com/breun/73e51484366450904947

**Comment by gr2m** [comment]
What was before `npm sill install resolved []`?

**Comment by gr2m** [comment]
I’m running a bit out of ideas :/ Did you ever install something with `sudo npm install`?

Can you try `npm config set registry http://registry.npmjs.org/`. If it doesn't help, reset it with `npm config set registry https://registry.npmjs.org/`

**Comment by breun** [comment]
After running `npm config set registry http://registry.npmjs.org/` the `npm install` command finished successfully. I'm not a big fan of disabling HTTPS though.

I recently also had an issue with git clones done by MacPorts failing because of a certificate issue: https://trac.macports.org/ticket/50469

These issues might have the same root cause (my `npm` is also installed via MacPorts), but in both cases I just don't get enough information from the logging to find out what's really wrong. :(

**Comment by gr2m** [comment]
try to uninstall your node & npm entirely, and install it as advised on https://nodejs.org/en/

**Comment by breun** [comment]
Yeah sorry, no, not gonna do that. I prefer finding and fixing the cause of this issue to starting over with an npm install not managed by a package manager.

I have a fix ready though.

**Comment by gr2m** [comment]
fixed via https://github.com/hoodiehq/hoodie-server-account/pull/86. Thanks a ton @breun :+1: 

We have more starter issues if you’d like to give it another spin: http://go.hood.ie/hoodie-starter-issues
I’ve also invited you to the https://github.com/hoodiehq/ contributors team, welcome :)

**Comment by breun** [comment]
I'm actually not doing much JavaScript normally, but I enjoy seeing how this project deals with issues, tests, getting people involved, etc., so I might just fix a few issues if I can find the time. Thanks for the invite.

**Comment by gr2m** [comment]
Glad to hear that, thanks for the feedback :)

**Comment by nolanlawson** [comment]
`rm -fr node_modules && npm cache clear && npm install` is often a good choice for stuff like this. I agree node/npm can be a pain when it gets into a weird state, though, and a full reinstall is sometimes necessary (especially if `sudo` was ever, ever involved...).
