### ISSUE TITLE
PUT /session to return 400 Bad Request for invalid ?include=<path>

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#87]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

---

### :bug: The Bug

`hoodie-server-account` is implementing a [JSON API](http://jsonapi.org/format/#fetching-includes). The spec says that if passing an invalid path for the `?include=<path>` query parameter, the server must respond with a `400 Bad Request` error. But instead the server currently returns `403 Forbidden`

### :clipboard: Steps to fix

- [x] claim this issue (@c-ro)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Adjust the test in [tests/integration/routes/session-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/6b72426/tests/integration/routes/session-test.js#L428-L446) to assert that the server will respond with `400` statusCode and `”Bad Request”` title.
- [x] Make sure tests fail when you run `npm test`. Commit with the message `test: 401 invalid ?include=<path> -> 400 Bad Request`
- [x]  Pull Request #88
- [x] Fix the implementation :)
- [x] Make sure tests pass. Commit with `fix: invalid ?include=<path> -> 400 Bad Request`
- [x] You are done :clap: comment below that your pull request is ready for review 

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by c-ro** [comment]
I'll take this if nobody else has.

**Comment by gr2m** [comment]
All yours :+1:

**Comment by c-ro** [comment]
I've got the test written/failing but:

Get this error when trying to create PR:

> ERROR: Permission to hoodiehq/hoodie-server-account.git denied to c-ro.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.


I tried to skip the PR and save until I'd made some changes but I can't seem to locate code that needs to be fixed in the first place.  What am I missing?

**Comment by gr2m** [comment]
I think you tried pushing your branch to https://github.com/hoodiehq/hoodie-server-account, not your fork? I can add you as collaborator to fix that :)

**Comment by c-ro** [comment]
Thanks for your help, should be ready!

**Comment by gr2m** [comment]
merged via https://github.com/hoodiehq/hoodie-server-account/pull/88

Great work @c-ro, thanks a lot :)

We have some more starter issue if you like: http://go.hood.ie/hoodie-starter-issues There are also some which are more challenging that you see when you remove the "starter" label from the filters

**Comment by gr2m** [comment]
released with https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.4 :ship:

**Comment by c-ro** [comment]
Thanks for the patience and kinds words @gr2m!  I'll try to knock out another issue when I get a chance.

**Comment by nickcolley** [comment]
Thanks Ryan :D :tada:
