### ISSUE TITLE
Error message if "authorization" Header is not allowed

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#92]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

Both `PUT /session` and `PUT /session/account` do not allow an `authorization` header, as these are requests to sign in and sign up – neither makes sense if user is already signed in. Currently the server returns the error message `child "authorization" fails because ["authorization" is not allowed]` which is pretty cryptic.

### :dart: The goal

Instead of the cryptic error message, we would like the server to respond with `Authorization header not allowed`

### :clipboard: Step by Step

- [x] claim this issue (@alinebastos)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment these tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/e3c2ab35f030b47dde4a82dcd3fda887d9a0042c/tests/integration/utils/authorization-header-not-allowed-error.js#L17-L18).
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: error message for forbidden "authorization" header`
- [x] Start a Pull Request. Add `fixes #92` to the description.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/76be3f3/routes/utils/validations.js#L14-L15)
- [x] Make sure tests pass. Commit with `fix: error message for forbidden "authorization" header`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by alinebastos** [comment]
Hi, I'm claiming this issue for my first PR :)
I don't know where to assign.

**Comment by nickcolley** [comment]
Hey @alinebastos I've updated the issue so you're assigned, thanks for looking into this. :<)

**Comment by nickcolley** [comment]
:tada: Thanks for contributing @alinebastos ! Congrats on your first PR too :dancer:   http://firstpr.me/#alinebastos :P

**Comment by alinebastos** [comment]
Thanks :dancer: :octocat:

**Comment by gr2m** [comment]
:clap: great work everyone :)

**Comment by gr2m** [comment]
Hey @alinebastos, are you on Twitter? Would you mind us give you a shout out on https://twitter.com/hoodiehq?

**Comment by gr2m** [comment]
okay sorry, that already happened: https://twitter.com/hoodiehq/status/705766091117699073 :D

**Comment by alinebastos** [comment]
:D :D

On Thu, Mar 10, 2016 at 5:59 PM, Gregor Martynus <notifications@github.com>
wrote:

> okay sorry, that already happened:
> https://twitter.com/hoodiehq/status/705766091117699073 :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hoodiehq/hoodie-server-account/issues/92#issuecomment-195045730>
> .
>



-- 
Aline Bastos
