### ISSUE TITLE
When authorization is required but missing, return with 401

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#94]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

Requests like `GET /session/account` require a valid session. The server validates the session by parsing the `authorization` request header. If it does not exist for routes where it is required, the server currently responds with return `403`

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/account/fetch), the server should respond with `401 Unauthorized – Authorization header missing` instead of `403`.

### :clipboard: Step by Step

- [x] claim this issue (@alisabzevari)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/get-session-test.js#L38-L44)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: 401 authorization header missing`
- [x] Start a Pull Request #107
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/utils/validations.js)
- [x] Make sure tests pass, run them with `./node_modules/.bin/tap tests/integration/routes/session/get-session-test.js` this time. Commit with `fix: 401 authorization header missing`
- [x] now run tests with `npm test`. You will see that other tests fail because of your changes. Adjust them as you did in tests/integration/routes/session/get-session-test.js until all tests pass
- [x] commit with `test: 401 authorization header missing`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by alisabzevari** [comment]
Hi, I want to contribute on this issue as my first one!

**Comment by gr2m** [comment]
yaaay all yours :)

**Comment by alisabzevari** [comment]
Here is the PR: https://github.com/hoodiehq/hoodie-server-account/pull/107

**Comment by gr2m** [comment]
released as [v2.6.9](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.9) :+1:
