### ISSUE TITLE
DELETE /session: 404 should be 401

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#96]
part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

The handler for the  [DELETE /session route](https://github.com/hoodiehq/hoodie-server-account/blob/61798c9/routes/session.js#L135-L181) currently returns 404 if a session is invalid.

### :dart: The goal

But in our [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-out) we define `401` as the error code for an invalid session, so the correct server response should be `401 Unauthorized – Session invalid`

### :clipboard: Step by Step

- [x] claim this issue (@alexeyzab)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] We currently test for a `404` status [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/delete-session-test.js#L47-L50) and [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/tests/integration/routes/session/delete-session-test.js#L86-L89). Replace it with `401`. Also: `.title` should be `'Unauthorized'` and add an assertion for `.detail` which must be `'Session invalid'`
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test: DELETE /session: 404 should be 401`
- [x] Start a Pull Request (#106)
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L161-L163) and for comparison [here](https://github.com/hoodiehq/hoodie-server-account/blob/eb95fad004917c0e0f3ebc87eaca0a56727f391f/routes/session.js#L62-L67)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix: DELETE /session: 404 should be 401`
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by alexeyzab** [comment]
Hi there! I'd like to claim this issue. Thanks!

**Comment by gr2m** [comment]
Welcome @alexeyzab :wave: the issue is all yours :) Don’t hesitate to ping us if you have any questions :)

**Comment by alexeyzab** [comment]
@gr2m Thank you! :)

**Comment by alexeyzab** [comment]
Hey @gr2m, the tests seem to be passing, but I am not entirely confident in my solution. Let me know, if there are things I should change or improve. Thank you!

**Comment by gr2m** [comment]
Thanks @alexeyzab, I’ll check it later today or latest tomorrow. But maybe somebody else from the Hoodie community is faster than me ;)

**Comment by alexeyzab** [comment]
Gotcha, thanks again!

**Comment by gr2m** [comment]
ugh I’m so sorry I didn’t get to look into it after all as promised, but looking at it now.

**Comment by alexeyzab** [comment]
Sure thing, yep, that's the one! It was a fun and pleasant experience, thank you for all your help! :)

**Comment by gr2m** [comment]
If you would like to contribute again, ping me, happy to help find something nice :) We are out of starter issues, but there are other things were we need help. Most important for us right now are the ones listed here: https://github.com/gr2m/milestones/issues/88

**Comment by alexeyzab** [comment]
Gotcha, looking forward to contributing again!

**Comment by gr2m** [comment]
fixed via #106
