### ISSUE TITLE
PUT /session/account 409 error message

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#97]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

When signing up with`PUT /session/account` and sending a `username` in the request body as defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/session/sign-up), there is a possibility that the username is already taken. If that happens, the server should return `409 Conflict` error. That already happens, but the error message is `Document update conflict` (which is the default message coming from CouchDB, which we use as database). 

### :dart: The goal

If a username is taken, the server should respond with `409 Conflict` and the message `An account with that username already exists`.

### :clipboard: Step by Step

- [x] claim this issue (@roubaeli)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Update the assertion in [tests/integration/routes/account/put-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/tests/tests/integration/routes/account/put-account-test.js#L92) to test for the desired error message
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PUT /session/account 409 error message`
- [x] Start a Pull Request: #112
- [ ] Implement :) 
- [ ] Make sure tests pass. Commit with `fix: PUT /session/account 409 error message`
- [ ] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by roubaeli** [comment]
Can I claim this issue for my first PR?

**Comment by gr2m** [comment]
absolutely :) I assigned the issue to you, thanks for looking into it Eliška

**Comment by gr2m** [comment]
yaaay :tada: welcome to Hoodie :dog: and CONGRATULATIONS TO YOUR FIRST PR :star2: :clap: :+1: 

I’ve invited you to the Hoodie team, you should see the invitation on top of https://github.com/hoodiehq

We love giving shout outs to our newest contributors on Twitter. Do you have a twitter account? 

If you would like to look into something else, have any questions or just want to hang out, come join us in our [Hoodie Chat](http://hood.ie/chat/) :)

**Comment by gr2m** [comment]
released as [v2.6.18](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.18)

**Comment by roubaeli** [comment]
Yes I have (@roubaeli) :-) Thanks for great guidance. Hope I'm gonna be able to do that for someone someday.

**Comment by gr2m** [comment]
@roubaeli it was our pleasure :) If you like, you are more than welcome to help us prepare starter issues like this one :) We have this big list here that still has several inconsistencies: https://github.com/hoodiehq/hoodie-server-account/issues/83 for which we can prepare starter issues. We also blogged about how we prepare these kind of issues here: http://hood.ie/blog/starter-issues.html :)
