### ISSUE TITLE
GET /session/account: "404 Admins have no accounts" error

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#98]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

We differentiate between normal user accounts that you can sign up for with `PUT /session/account` and admin accounts which are configured in the app configuration. The latter have no account or profile, they are only used to manage other accounts and other app settings.

`GET /session/account` is already implemented correctly, the only problem is that we currently respond with a `403` status code, although after discussing it we agreed that `404` would be the better error code here.

### :dart: The goal

For admin users, `GET /session/account` should respond with `404 Not found` and the error message "Admins have no accounts"

### :clipboard: Step by Step

- [x] claim this issue (@stevemasta34)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [ ] Update the assertion in [tests/integration/routes/account/get-account-test.js](https://github.com/hoodiehq/hoodie-server-account/blob/a94b05b99237994d5f8730f185c5beaefb1f9e6d/tests/integration/routes/account/get-account-test.js#L87-L89) to test for `404` and the desired error message
- [ ] Make sure tests fail when you run `npm test`
- [ ] Commit with `test(routes): GET /session/account behavior for admins`
- [ ] Start a Pull Request.  
<small>(If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request)</small>
- [ ] Implement :) 
- [ ] Make sure tests pass. Commit with `fix(routes): GET /session/account behavior for admins`
- [ ] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by stevemasta34** [comment]
I'd love a swing at this one. Seems very straight forward

**Comment by gr2m** [comment]
Thanks @stevemasta34 and congratulations, not only to your first contribution to Hoodie :tada: :dog: but to your First PR :fireworks: :clap: :dancers: http://firstpr.me/#stevemasta34

We happily invite you to our @hoodiehq/contributors team. If you like, you can accept the invitation here: https://github.com/hoodiehq (you probably received an email notification from GitHub, too)

If you don’t mind sharing, could you tell a bit about yourself, how you learned about Hoodie, how you liked the experience to contribute to Hoodie, if there is anything we could improve?

**Comment by gr2m** [comment]
The new version was released as [v2.6.6](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.6) :+1:
