### ISSUE TITLE
PATCH /session/account -> 204 

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-server-account#99]
This is a [starter issue](http://hood.ie/blog/starter-issues.html). It’s part of https://github.com/hoodiehq/hoodie-server-account/issues/83

### :octocat:  Your First Pull Request?

We would like to take the opportunity to invite someone who did not yet contribute to Hoodie to work on this issue. Follow [@YourFirstPR](https://twitter.com/yourfirstPR) on Twitter for more of these issues across many open source projects :)

### :bug: The Bug

To change username or password, user send a `PATCH /session/account` request with the changed attributes. Right now the server respondes with `201` and the account properties.

### :dart: The goal

As defined in the [Account JSON API Spec](http://docs.accountjsonapi.apiary.io/#reference/current-user/account/update), the server should respond with an empty `204`

### :clipboard: Step by Step

- [x] claim this issue (@bartw)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-server-account/blob/master/tests/README.md#testing) and make sure that all tests pass
- [x] Uncomment tests [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/tests/integration/routes/account/patch-account-test.js#L116-L119)
- [x] Make sure tests fail when you run `npm test`
- [x] Commit with `test(routes): PATCH /session/account -> 204 `
- [x] Start a Pull Request: #115 
- [x] Implement :) Spoiler alert: If you get stuck, you might want to look [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/routes/account.js#L155) and compare to [here](https://github.com/hoodiehq/hoodie-server-account/blob/f105951831d51b9af57d535c43802dd65f023c69/routes/session.js#L171)
- [x] Make sure tests pass when you run `npm test`. Commit with `fix(routes): PATCH /session/account -> 204 `
- [x] Done :+1: Ask in comments for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by bartw** [comment]
I started a pull request for this issue

**Comment by gr2m** [comment]
Thank you @bartw – your fix has been released in [v2.6.10](https://github.com/hoodiehq/hoodie-server-account/releases/tag/v2.6.10) :clap: 

We are stoked that Hoodie is the very first project you ever contributed to: http://firstpr.me/#bartw I hope it was a nice experience for you, welcome to the open source community :tada:

And welcome to Hoodie :dog: We happily invite you to the Contributors Team. You should get an invitation per email, and can also see it on https://github.com/hoodiehq. As part of the team, you can create branches directly on our repositories, and also be part of a fun gang :) Hang out with us in the [Hoodie Chat](http://hood.ie/chat/)

If you like to contribute something again, we are currently working on a new Hoodie Release and a few things are still on the list: https://github.com/gr2m/milestones/issues/88

**Comment by gr2m** [comment]
Oh one thing: are you on Twitter? If yes, would you mind if we give a shout out at https://twitter.com/hoodiehq?

**Comment by bartw** [comment]
I'm on twitter. You can shout me out at https://twitter.com/BartWijnants
